### ISSUE TITLE
Requires extremely high SDK versions

### ISSUE THREAD

**Issue by Akshiiitsaxena** [rafalbednarczuk/curved_navigation_bar#1]
requires SDK version >=2.1.0. Current version 2.1.0-dev

**Comment by rafalbednarczuk** [comment]
fixed in:
https://github.com/rafalbednarczuk/curved_navigation_bar/commit/56dc445129bc44114e4bb06abbe47b071e632c0c
Also, I recommend using dev flutter dev channel in order to use the newest and latest functions from flutter.
