### ISSUE TITLE
box shadow

### ISSUE THREAD

**Issue by dimiandre** [rafalbednarczuk/curved_navigation_bar#10]
Would be nice to have the possibility to add a box shadow to the navbar in case i want to have both the background and the nav white

**Comment by rafalbednarczuk** [comment]
I don't get your point. Can you explain it?

**Comment by dimiandre** [comment]
> I don't get your point. Can you explain it?

like this

<img width="408" alt="Screenshot 2019-03-20 at 11 11 27" src="https://user-images.githubusercontent.com/543292/54676413-f42a3200-4b00-11e9-9065-b3157848f5e9.png">

**Comment by rafalbednarczuk** [comment]
It requires some work to make this feature and transparent navigation bar work together. Will look at it.

**Comment by gibbsvjy007** [comment]
is there any update on it ?

**Comment by lucasjinreal** [comment]
I have a customized version to do this:

![image](https://user-images.githubusercontent.com/21303438/87749975-ba6c5700-c82c-11ea-944e-3bce40f807a3.png)

**Comment by muk-y** [comment]
> I have a customized version to do this:
> 
> ![image](https://user-images.githubusercontent.com/21303438/87749975-ba6c5700-c82c-11ea-944e-3bce40f807a3.png)

Can you please help me out too to do it?

**Comment by baali-boudjemaa** [comment]
> > I have a customized version to do this:
> > ![image](https://user-images.githubusercontent.com/21303438/87749975-ba6c5700-c82c-11ea-944e-3bce40f807a3.png)
> 
> Can you please help me out too to do it?

**Comment by NaarGes** [comment]
do you have any plan to support this?

**Comment by rafalbednarczuk** [comment]
> do you have any plan to support this?

no plans to support this
