### ISSUE TITLE
Bottom bar move up when keyboard appears. Although resizeToAvoidBottomInset is false

### ISSUE THREAD

**Issue by ctykaya** [rafalbednarczuk/curved_navigation_bar#105]
When I update the flutter to 2.2.2 this problem occurs. When I select input field keyboard appears but bottom bar is stick top of the keyboard. How can I fix it ?

pubspec.yaml file
curved_navigation_bar: ^1.0.1

**Comment by rafalbednarczuk** [comment]
set `resizeToAvoidBottomInset` to `false` in Scaffold widget

**Comment by ctykaya** [comment]
I set it but it does not work. Same problem
