### ISSUE TITLE
Blank Screen on navigation

### ISSUE THREAD

**Issue by iamaryanshandilya** [rafalbednarczuk/curved_navigation_bar#106]
I am using this package in a project, though there's a problem. Say there are two screens a, b. When going to some other screen c that is not a part of the bottom navigation bar. When I press the back button on the app bar I get a blank screen.
[https://stackoverflow.com/questions/62276420/back-button-inside-appbar-showing-black-screen-in-flutter](url)  addresses this issue but I am having trouble implementing it. Can I get to know how to solve this?

**Comment by rafalbednarczuk** [comment]
Was answered in the SO thread.
