### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by eslamhalaweh** [rafalbednarczuk/curved_navigation_bar#109]
How can the curved navigation bar be persisted across screens?
(i.e: make this navigation bar persistent).
When i navigate routes, the navigation bar disappears.

**Comment by rafalbednarczuk** [comment]
It's not going to be implemented into this package. 
Also, I think the package shouldn't be used that way. You should put another navigation inside the body of the Scaffold, which has a bottom navigation bar. 
This way the CurvedNavigationBar is static, while navigation happens deeper in the tree level
