### ISSUE TITLE
Duplicated GlobalKey when a key is added on the menu items

### ISSUE THREAD

**Issue by jordygarcias** [rafalbednarczuk/curved_navigation_bar#110]
I need to add a globalkey on each of the menus, but it gets the error of duplication of GlobalKey. It says there are more than 1 widget using the same globalkey, it just happens with the active item of the menu.

**Comment by rafalbednarczuk** [comment]
This bug is probably due having a duplicated menu button widget, animation requires an active item and a non-active item while animating. Feel free to open a PR.

**Comment by rafalbednarczuk** [comment]
it would require a separate list of items with separate global keys, I'm not implementing it at the moment as items can be uploaded by simply updating `items` property. 
There is a workaround for using GlobalKeys
