### ISSUE TITLE
Bottom bar move up above keyboard when it appears. Although resizeToAvoidBottomInset is false

### ISSUE THREAD

**Issue by xSuperMu** [rafalbednarczuk/curved_navigation_bar#114]
<img width="438" alt="Screen Shot 2021-10-28 at 9 11 05 AM" src="https://user-images.githubusercontent.com/17935590/139205036-8f8207bd-e04f-46a9-90fd-244b9db66733.png">

**Comment by rafalbednarczuk** [comment]
Duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/105
It's not a bug of this package, probably a bug with your code not related with the package
