### ISSUE TITLE
Background Color not Transparent

### ISSUE THREAD

**Issue by itsdani121** [rafalbednarczuk/curved_navigation_bar#115]
Hi, i tried all answers in #31 but did not work any answers that's why i am creating a new issue that the background of nav bar not changed here is my code:
 
              Scaffold(
            extendBody: true,  // here is extendbody set
            bottomNavigationBar: CurvedNavigationBar(
              color: Color(int.parse('$newColor')),
              backgroundColor: Colors.transparent, // here is background color set
              key: _bottomsKey,
              height: 50,
              items: [
          // here those nav screen shown according to list 
            ]
            ),
            body: WillPopScope(
                onWillPop: _onWillPop, child: resultScreens[_page]),
          );

kindly look into this and guide me if i am wrong this is my navbar class.

**Comment by jsdaniell** [comment]
I also with the same problem here is my widget:

```dart
 @override
  Widget build(BuildContext context) {
    final HomeScreenController controller = Get.put(HomeScreenController());

    return Container(
      color: CustomCollors.purpleColor,
      child: SafeArea(
        top: false,
        child: ClipRect(
          child: Obx(() => Scaffold(
            extendBody: true,
              bottomNavigationBar: CurvedNavigationBar(
                backgroundColor: Colors.transparent,
                index: controller.selectedTab.value,
                color: CustomCollors.purpleColor,
                animationDuration: const Duration(milliseconds: 300),
                animationCurve: Curves.easeInOutQuad,
                buttonBackgroundColor: CustomCollors.purpleColor,
                items: const <Widget>[
                  Icon(
                    Icons.change_circle_rounded,
                    size: 30,
                    color: CustomCollors.whiteColor,
                  ),
                  Icon(
                    Icons.home_rounded,
                    size: 30,
                    color: CustomCollors.whiteColor,
                  ),
                  Icon(
                    Icons.account_circle,
                    size: 30,
                    color: CustomCollors.whiteColor,
                  ),
                ],
                onTap: (index) {
                  /// Code to push to some tab from outside onTap
                  /// final navigationState = _navigationTabKey.currentState!;
                  /// navigationState.setPage(index);

                  controller.changeSelectedTab(index);
                },
              ),
              body: screens[controller.selectedTab.value]
          )),
        ),
      ),
    );
  }
  ```

`extendBody` doesn't work.

**Comment by itsdani121** [comment]
@rafalbednarczuk plz look into this matter

**Comment by Nishank00** [comment]
@jsdaniell 
Please follow this code, it worked for me
CurvedNavigationBar(
backgroundColor: Colors.transparent,
),

For body of Curved Nav Bar
SafeArea(
bottom: false
);

PS: Sorry for bad formatting

**Comment by itsdani121** [comment]
@Nishank00 i did but not work

**Comment by Nishank00** [comment]
@itsdani121  
![Screenshot_20220113-100818](https://user-images.githubusercontent.com/41135445/149266866-2506d14c-a6d2-421e-826b-e3e84ed7e3dc.jpg)

I was able to achieve this by removing safearea from bottom(false),  I have two classes one for my bottom nav bar and one for the homepage both have extendbody true and Safearea bottom false

**Comment by itsdani121** [comment]
@Nishank00  ok i understand this thanks so basically in a class where nav bar attach set background color transparent and which classes added as list in their safeare set bottom false then it works..

**Comment by Nishank00** [comment]
@itsdani121 

Class for CurvedNavBar
class DashPage extends StatefulWidget {
  const DashPage({Key? key}) : super(key: key);

  @override
  _DashPageState createState() => _DashPageState();
}

class _DashPageState extends State<DashPage> {
  int _page = 0;
  final GlobalKey<CurvedNavigationBarState> _bottomNavigationKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        extendBody: true,
        bottomNavigationBar: CurvedNavigationBar(
          key: _bottomNavigationKey,
          index: 0,
          height: 60.0,
          items: const <Widget>[
            Icon(Icons.home_filled, size: 30, color: Colors.white),
            //Icon(Icons.calendar_today, size: 30, color: Colors.white),
            Icon(Icons.school, size: 30, color: Colors.white),
            //Icon(Icons.book, size: 30, color: Colors.white),
            Icon(Icons.person, size: 30, color: Colors.white),
          ],
          color: primaryColor,
          buttonBackgroundColor: primaryColor,
          animationCurve: Curves.easeInOut,
          backgroundColor: Colors.transparent,
          animationDuration: const Duration(milliseconds: 600),
          onTap: (index) {
            setState(() {
              _page = index;
            });
          },
          letIndexChange: (index) => true,
        ),
        body: _page == 0
            ? HomePage()
            : _page == 1
                ? CoursesPage()
                : _page == 2
                    ? ProfilePage()
                    : Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Text(_page.toString(), textScaleFactor: 10.0),
                            ElevatedButton(
                              child: const Text('Go To Page of index 0'),
                              onPressed: () {
                                final CurvedNavigationBarState? navBarState =
                                    _bottomNavigationKey.currentState;
                                navBarState?.setPage(0);
                              },
                            )
                          ],
                        ),
                      ));
  }
}


Code for Index 0: Homepage

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    double h = MediaQuery.of(context).size.height;
    double w = MediaQuery.of(context).size.width;
    return Scaffold(
      extendBody: true,
      body: SafeArea(
          bottom: false,
          child: Container(
            padding: EdgeInsets.all(0.0),
            child: SingleChildScrollView(
              child: Column(
                children: [
                  Container(
                    padding: EdgeInsets.all(15.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "Welcome to,",
                              style: TextStyle(
                                  color: Colors.black54,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 18.0),
                            ),
                            Text('VTI Students',
                                style: TextStyle(
                                    color: primaryColor,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 25.0))
                          ],
                        ),
                        IconButton(
                            onPressed: () {
                              Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                      builder: (context) =>
                                          NotificationsPage()));
                            },
                            icon: Icon(
                              Icons.notifications,
                              color: primaryColor,
                            ))
                      ],
                    ),
                  ),
                  SizedBox(
                    height: h * 0.03,
                  ),
                  Container(
                    height: h * 0.25,
                    width: w,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.all(
                        Radius.circular(0.0),
                      ),
                      image: DecorationImage(
                        image: AssetImage("assets/images/video_lectures.png"),
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                  SizedBox(
                    height: h * 0.04,
                  ),
                  Row(
                    children: [
                      SizedBox(
                        width: 15.0,
                      ),
                      Text(
                        "Starter Pack Videos",
                        style: TextStyle(
                            color: Colors.black87,
                            fontWeight: FontWeight.bold,
                            fontSize: 24),
                      ),
                      Icon(
                        Icons.arrow_forward,
                        color: primaryColor,
                        size: 30,
                      )
                    ],
                  ),
                  SizedBox(
                    height: h * 0.02,
                  ),
                  Container(
                    height: h * 0.25,
                    child: ListView.builder(
                        shrinkWrap: true,
                        primary: false,
                        scrollDirection: Axis.horizontal,
                        itemCount: 5,
                        itemBuilder: (context, index) {
                          if (index == 4) {
                            return InkWell(
                              onTap: () {
                                Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                        builder: (context) =>
                                            VideoLecturesPage()));
                              },
                              child: Container(
                                padding: EdgeInsets.symmetric(horizontal: 10.0),
                                child: Row(
                                  children: [
                                    Text(
                                      "View All",
                                      style: TextStyle(
                                        color: Colors.black54,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                    SizedBox(
                                      width: 5.0,
                                    ),
                                    Icon(
                                      Icons.arrow_forward,
                                      color: primaryColor,
                                    )
                                  ],
                                ),
                              ),
                            );
                          }
                          return InkWell(
                            onTap: () {
                              Navigator.push(
                                  context,
                                  MaterialPageRoute(
                                      builder: (context) =>
                                          VideoDetailsPage()));
                            },
                            child: Container(
                              height: h * 0.3,
                              width: w * 0.6,
                              margin: EdgeInsets.symmetric(horizontal: 5.0),
                              child: Card(
                                elevation: 3.0,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(14.0)),
                                child: Container(
                                  padding: EdgeInsets.all(0.0),
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    children: [
                                      Container(
                                        height: h * 0.15,
                                        decoration: BoxDecoration(
                                            borderRadius: BorderRadius.all(
                                              Radius.circular(14.0),
                                            ),
                                            image: DecorationImage(
                                                image: AssetImage(
                                                    "assets/images/video_lectures.png"),
                                                fit: BoxFit.cover)),
                                      ),
                                      SizedBox(
                                        height: 10,
                                      ),
                                      Container(
                                        padding: EdgeInsets.symmetric(
                                            horizontal: 15.0),
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              "Programming with Java",
                                              maxLines: 1,
                                              overflow: TextOverflow.ellipsis,
                                              style: TextStyle(
                                                  color: Colors.black87,
                                                  fontWeight: FontWeight.bold,
                                                  fontSize: 15.0),
                                            ),
                                            Text(
                                              "By Prof. Shalini Singh",
                                              style: TextStyle(
                                                  color: Colors.black54,
                                                  fontWeight: FontWeight.bold),
                                            )
                                          ],
                                        ),
                                      )
                                    ],
                                  ),
                                ),
                              ),
                            ),
                          );
                        }),
                  ),
                  SizedBox(
                    height: h * 0.04,
                  ),
                  Container(
                    margin: EdgeInsets.symmetric(horizontal: 15.0),
                    height: h * 0.2,
                    decoration: BoxDecoration(
                        borderRadius: BorderRadius.all(
                          Radius.circular(14.0),
                        ),
                        image: DecorationImage(
                            image: AssetImage("assets/images/image2.jpg"),
                            fit: BoxFit.cover)),
                  ),
                  SizedBox(
                    height: h * 0.03,
                  ),
                  Container(
                    height: h * 0.05,
                    child: Center(
                      child: ListView.builder(
                          shrinkWrap: true,
                          scrollDirection: Axis.horizontal,
                          physics: NeverScrollableScrollPhysics(),
                          itemCount: 4,
                          itemBuilder: (context, index) {
                            return Container(
                              width: w * 0.2,
                              margin: EdgeInsets.symmetric(horizontal: 5.0),
                              padding: EdgeInsets.all(8.0),
                              decoration: BoxDecoration(
                                  border: Border.all(
                                      color: primaryColor, width: 2.0),
                                  borderRadius:
                                      BorderRadius.all(Radius.circular(20.0))),
                              child: index % 2 == 0
                                  ? Center(
                                      child: Text(
                                        "Flutter",
                                        style: TextStyle(
                                            color: primaryColor,
                                            fontWeight: FontWeight.bold),
                                      ),
                                    )
                                  : Center(
                                      child: Text(
                                        "Python",
                                        style: TextStyle(
                                            color: primaryColor,
                                            fontWeight: FontWeight.bold),
                                      ),
                                    ),
                            );
                          }),
                    ),
                  ),
                  SizedBox(
                    height: h * 0.03,
                  ),
                  Row(
                    children: [
                      SizedBox(
                        width: 15.0,
                      ),
                      Text(
                        "Our Blog",
                        style: TextStyle(
                            color: Colors.black87,
                            fontWeight: FontWeight.bold,
                            fontSize: 24),
                      ),
                      Icon(
                        Icons.arrow_forward,
                        color: primaryColor,
                        size: 30,
                      )
                    ],
                  ),
                  SizedBox(
                    height: h * 0.02,
                  ),
                  Container(
                    height: h * 0.35,
                    child: ListView.builder(
                        shrinkWrap: true,
                        primary: false,
                        scrollDirection: Axis.horizontal,
                        itemCount: 5,
                        itemBuilder: (context, index) {
                          if (index == 4) {
                            return InkWell(
                              onTap: () {
                                Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                        builder: (context) => BlogListPage()));
                              },
                              child: Container(
                                padding: EdgeInsets.symmetric(horizontal: 10.0),
                                child: Row(
                                  children: [
                                    Text(
                                      "View All",
                                      style: TextStyle(
                                        color: Colors.black54,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                    SizedBox(
                                      width: 5.0,
                                    ),
                                    Icon(
                                      Icons.arrow_forward,
                                      color: primaryColor,
                                    )
                                  ],
                                ),
                              ),
                            );
                          }
                          return Container(
                            height: h * 0.35,
                            width: w * 0.6,
                            margin: EdgeInsets.symmetric(horizontal: 5.0),
                            child: Card(
                              elevation: 3.0,
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(14.0)),
                              child: Container(
                                padding: EdgeInsets.all(10.0),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceEvenly,
                                  children: [
                                    Container(
                                      height: h * 0.15,
                                      decoration: BoxDecoration(
                                          borderRadius: BorderRadius.all(
                                            Radius.circular(14.0),
                                          ),
                                          image: DecorationImage(
                                              image: index % 2 == 0
                                                  ? AssetImage(
                                                      "assets/images/notifications.jpg")
                                                  : AssetImage(
                                                      "assets/images/notifications2.jpg"),
                                              fit: BoxFit.cover)),
                                    ),
                                    Text(
                                      "Harness the Power of Flutter",
                                      maxLines: 2,
                                      overflow: TextOverflow.ellipsis,
                                      style: TextStyle(
                                          color: Colors.black87,
                                          fontWeight: FontWeight.bold,
                                          fontSize: 15.0),
                                    ),
                                    Row(
                                      children: [
                                        Icon(
                                          Icons.remove_red_eye,
                                          color: Colors.blueGrey,
                                        ),
                                        SizedBox(
                                          width: 5.0,
                                        ),
                                        Text(
                                          "299 Views",
                                          style: TextStyle(
                                              color: Colors.grey.shade400,
                                              fontWeight: FontWeight.bold),
                                        )
                                      ],
                                    ),
                                    Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        Text(
                                          "By XYZ",
                                          style: TextStyle(
                                              color: Colors.black54,
                                              fontWeight: FontWeight.bold),
                                        ),
                                        Icon(
                                          Icons.arrow_forward,
                                          color: Colors.amber,
                                        )
                                      ],
                                    )
                                  ],
                                ),
                              ),
                            ),
                          );
                        }),
                  ),
                  SizedBox(
                    height: h * 0.04,
                  ),
                  Row(
                    children: [
                      SizedBox(
                        width: 15.0,
                      ),
                      Text(
                        "Why Us?",
                        style: TextStyle(
                            color: Colors.black87,
                            fontWeight: FontWeight.bold,
                            fontSize: 24.0),
                      ),
                      Icon(
                        Icons.arrow_forward,
                        color: primaryColor,
                        size: 30,
                      ),
                    ],
                  ),
                  SizedBox(
                    height: h * 0.02,
                  ),
                  Container(
                    height: h * 0.30,
                    child: ListView.builder(
                        shrinkWrap: true,
                        primary: false,
                        scrollDirection: Axis.horizontal,
                        itemCount: 5,
                        itemBuilder: (context, index) {
                          if (index == 4) {
                            return InkWell(
                              onTap: () {
                                Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                        builder: (context) =>
                                            WebViewReviews()));
                              },
                              child: Container(
                                padding: EdgeInsets.symmetric(horizontal: 10.0),
                                child: Row(
                                  children: [
                                    Text(
                                      "View All",
                                      style: TextStyle(
                                        color: Colors.black54,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                    SizedBox(
                                      width: 5.0,
                                    ),
                                    Icon(
                                      Icons.arrow_forward,
                                      color: primaryColor,
                                    )
                                  ],
                                ),
                              ),
                            );
                          }
                          return Container(
                            height: h * 0.30,
                            width: w * 0.6,
                            margin: EdgeInsets.symmetric(horizontal: 5.0),
                            child: Card(
                              elevation: 3.0,
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(14.0)),
                              child: Container(
                                padding: EdgeInsets.all(10.0),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  mainAxisAlignment:
                                      MainAxisAlignment.spaceEvenly,
                                  children: [
                                    Container(
                                      height: h * 0.07,
                                      width: h * 0.07,
                                      decoration: BoxDecoration(
                                          color: primaryColor,
                                          shape: BoxShape.circle,
                                          image: DecorationImage(
                                              image: AssetImage(
                                                  "assets/images/person.jpg"),
                                              fit: BoxFit.cover)),
                                    ),
                                    Text(
                                      '"Lorem Ipsum is simply dummy text of the printing and typesetting industry"',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          color: Colors.black54,
                                          fontWeight: FontWeight.bold),
                                    ),
                                    Row(
                                      children: [
                                        Text("Nishank S.",
                                            style: TextStyle(
                                                color: primaryColor,
                                                fontWeight: FontWeight.bold))
                                      ],
                                    )
                                  ],
                                ),
                              ),
                            ),
                          );
                        }),
                  ),
                  SizedBox(
                    height: h * 0.02,
                  ),
                ],
              ),
            ),
          )),
    );
  }
}

**Comment by Nishank00** [comment]
``

> @Nishank00 ok i understand this thanks so basically in a class where nav bar attach set background color transparent and which classes added as list in their safeare set bottom false then it works..

Yep

**Comment by jsdaniell** [comment]
After hours of coding, sometime I may have code something that's made the background transparent, I don't know what's exactly I did, but here's my actual code:

```dart
import 'package:allugaapp/auth/auth.dart';
import 'package:allugaapp/constants/colors.dart';
import 'package:allugaapp/constants/tags_controllers.dart';
import 'package:allugaapp/screens/account_tab_screen/account_tab_screen.dart';
import 'package:allugaapp/screens/chat_tab_screen/chat_tab_screen.dart';
import 'package:allugaapp/screens/home_screen/home_screen_controller.dart';
import 'package:allugaapp/screens/main_tab_screen/main_tab_screen.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final screens = <Widget>[
    const ChatTabScreen(),
    const MainTabScreen(),
    const AccountTabScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      color: AllugaColors.purpleColor,
      child: SafeArea(
        top: false,
        child: ClipRect(
          child: GetBuilder<HomeScreenController>(
            init: HomeScreenController(),
            tag: TagsControllers.homeScreenController,
            builder: (_) => Scaffold(
                extendBody: true,
                bottomNavigationBar: CurvedNavigationBar(
                  backgroundColor: _.selectedTab == 2
                      ? AllugaColors.darkPurpleColor
                      : Colors.transparent,
                  index: _.selectedTab,
                  color: AllugaColors.purpleColor,
                  animationDuration: const Duration(milliseconds: 300),
                  animationCurve: Curves.easeInOutQuad,
                  buttonBackgroundColor: _.selectedTab == 2
                      ? AllugaColors.whiteColor
                      : AllugaColors.purpleColor,
                  items: <Widget>[
                    const Icon(
                      Icons.all_inbox_rounded,
                      size: 30,
                      color: AllugaColors.whiteColor,
                    ),
                    const Icon(
                      Icons.home_rounded,
                      size: 30,
                      color: AllugaColors.whiteColor,
                    ),
                    Icon(
                      Icons.account_circle,
                      size: 30,
                      color: _.selectedTab == 2
                          ? AllugaColors.purpleColor
                          : AllugaColors.whiteColor,
                    ),
                  ],
                  onTap: (index) {
                    _.changeSelectedTab(index);
                  },
                ),
                body: screens[_.selectedTab]),
          ),
        ),
      ),
    );
  }
}
```

**Comment by cybex-dev** [comment]
To make

> @itsdani121 ![Screenshot_20220113-100818](https://user-images.githubusercontent.com/41135445/149266866-2506d14c-a6d2-421e-826b-e3e84ed7e3dc.jpg)
> 
> I was able to achieve this by removing safearea from bottom(false), I have two classes one for my bottom nav bar and one for the homepage both have extendbody true and Safearea bottom false

**Thanks to this, I have a working solution.**

---

### Solution

**See notes below on solution**

Example working with `ListView`:

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true, // required
      bottomNavigationBar: CurvedNavigationBar(
        height: 60,
        backgroundColor: Colors.transparent, // required
        buttonBackgroundColor: Colors.white,
        items: [
          IconButton(onPressed: () {}, icon: Icon(Icons.thumb_up)),
          IconButton(onPressed: () {}, icon: Icon(Icons.thumb_up)),
          IconButton(onPressed: () {}, icon: Icon(Icons.thumb_up)),
        ],
      ),
      body: Container(
        child: SafeArea( // if using this,
          bottom: false,  // then set this too
          child: ListView.builder(
            itemBuilder: (context, index) => ListTile(
              tileColor: Colors.primaries[index % Colors.primaries.length],
              title: Text("Item $index"),
            ),
            itemCount: 50,
          ),
        ),
      ),
    );
  }
```

#### Notes on solution:

_use the example in a `MaterialApp`/`CupertinoApp` or in a separate "screens" file_

Based on **Flutter: 2.8.1, Dart 2.15.1**

**Required:**
- `Scaffold(extendBody: true, ...)`
- `CurvedNavigationBar(backgroundColor: Colors.transparent,...)`

**Optionally:**
- Using a `SafeArea`, set `SafeArea(bottom: false,...)`
