### ISSUE TITLE
can i pause  animation at a specific index 

### ISSUE THREAD

**Issue by Mohammad-kanaan-alsharbaje** [rafalbednarczuk/curved_navigation_bar#122]
can i pause  animation at a specific index ?
how can i do that without any issue 
i tried  to do it but there is a lot  of issues
![لقطة الشاشة 2022-04-13 060738](https://user-images.githubusercontent.com/98219110/163107587-b53f8379-1df5-4cff-88c7-bb5c8bcb70d4.jpg)

**Comment by tavyDesign** [comment]
I'm also interested

**Comment by heshesh2010** [comment]
you can pause or resume animation when current index = 1 for example 


`   animationDuration: currentIndex== 1
                ? const Duration(milliseconds: 1)
                : const Duration(milliseconds: 300),`

don't forget to use set state or statemangment like getx to refresh the widget .

**Comment by rafalbednarczuk** [comment]
What do you want to achieve exactly?
I'll reopen the issue if you describe the problem so I know what's the issue
