### ISSUE TITLE
Bottom nav item flickering while scrolling on iOS

### ISSUE THREAD

**Issue by MohamedRashad99** [rafalbednarczuk/curved_navigation_bar#129]
![image](https://user-images.githubusercontent.com/42122633/185650596-ebcd209c-ce32-4047-9729-03de898b9160.png)
![image](https://user-images.githubusercontent.com/42122633/185650660-4c6bb936-6973-42bf-ac7f-61980071fc5b.png)

**Comment by rafalbednarczuk** [comment]
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/121
