### ISSUE TITLE
InitialIndex is not correctly used

### ISSUE THREAD

**Issue by panthe** [rafalbednarczuk/curved_navigation_bar#13]
InitialIndex is ignored because is hardcoded to 0.
This cause an incorrect icon in the case that you for example hide and show curved bar in different view.
initialIndex will be ignored and the current selected item take home icon.

If in curved_navigation_bar.dart you change line 19 from
this.initialIndex=0 to this.InitialIndex

and change the line 48 from
_icon = widget.items[0]; to _icon = widget.items[widget.initialIndex];

All works fine.

P.s. I would appreciate collaborate with you in this plugin if you want.

**Comment by rafalbednarczuk** [comment]
nice catch, fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/7b52608678c1eace0f731620f5d8f5936e369405
If you want to collaborate feel free to make pull requests
