### ISSUE TITLE
color: Color of NavigationBar, default Colors.white not change

### ISSUE THREAD

**Issue by tedyjuan** [rafalbednarczuk/curved_navigation_bar#144]
extendBody: true,
      bottomNavigationBar: CurvedNavigationBar(
        backgroundColor: Colors.transparent,
        onTap: (index) {},
        height: 60,
        color: Color(0xFF4C53A5), // color not working
        items: [
          CurvedNavigationBarItem(
              icon: const Icon(Icons.add, size: 30, color: Colors.white), label: "Add"),
          CurvedNavigationBarItem(
              icon: const Icon(Icons.list, size: 30, color: Colors.white), label: "List"),
          CurvedNavigationBarItem(
              icon: Icon(Icons.compare_arrows, size: 30, color: Colors.white), label: "Compare"),
        ],
      ),

**Comment by rafalbednarczuk** [comment]
It's working
![image](https://github.com/rafalbednarczuk/curved_navigation_bar/assets/14034293/e09e0ee2-a66f-4879-b504-2a0f7d9d8078)

Also, there is nothing like `CurvedNavigationBarItem` in my package, probably you are using a different package that has this bug
