### ISSUE TITLE
Error: Member not found: 'MediaQuery.sizeOf'.

### ISSUE THREAD

**Issue by budimanpranata** [rafalbednarczuk/curved_navigation_bar#145]
error curved_navigation_bar-1.0.5/lib/curved_navigation_bar.dart:119:44: Error: Member not found: 'MediaQuery.sizeOf'.
                  deviceHeight: MediaQuery.sizeOf(context).height,

**Comment by rafalbednarczuk** [comment]
fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/bd53cc460b6ac30786d1ab45f5371f59530f6c8b
thank you for the report, you should use at least version 3.10.0 of Flutter
