### ISSUE TITLE
After upgrading to version 1.0.6, the click effect is not as good as that of 1.0.4. What's going on?

### ISSUE THREAD

**Issue by xiongzhaoxu** [rafalbednarczuk/curved_navigation_bar#146]
After upgrading to version 1.0.6, the click effect is not as good as that of 1.0.4. What's going on?

**Comment by rafalbednarczuk** [comment]
Please add more details to this issue, I didn't notice anything related different to hit detection.
2 videos of 2 different versions with clicks visible would be great

**Comment by msnnyusos** [comment]
https://github.com/rafalbednarczuk/curved_navigation_bar/assets/170705693/b2a7259f-c2b7-4cee-bf84-78cf66817f56


https://github.com/rafalbednarczuk/curved_navigation_bar/assets/170705693/de58b8e5-be54-485e-8b3a-f7959399804e

The codes of the two videos are the same, but the versions of curved_navigation_bar are different;

In the video of curved_navigation_bar_v1.0.4, you can see that clicking on the card is very smooth and sensitive; in the video of curved_navigation_bar_v1.0.6, clicking on the card feels sluggish, which is not a good experience;

I used the old versions before 1.0.4 (including 1.0.4) and they were very smooth. After the upgrade, the sluggish problem appeared, which felt very bad;

**Comment by msnnyusos** [comment]
flutter --version    
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (2 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by msnnyusos** [comment]
> Please add more details to this issue, I didn't notice anything related different to hit detection. 2 videos of 2 different versions with clicks visible would be great

Please see the two videos above, which illustrate this problem, the problem of not clicking smoothly

**Comment by rafalbednarczuk** [comment]
Okay, I understand that.
This is done on purpose, so user can not change the page when current page change is already in progress.

I think I might improve it in future, so it's still possible to click on different page while the current page is changing.

For now, you can use 1.0.4 or maybe change duration of animation so it takes less amount of time to change the page again.

I'm closing it as it's not the issue.

**Comment by msnnyusos** [comment]
> Okay, I understand that. This is done on purpose, so user can not change the page when current page change is already in progress.
> 
> I think I might improve it in future, so it's still possible to click on different page while the current page is changing.
> 
> For now, you can use 1.0.4 or maybe change duration of animation so it takes less amount of time to change the page again.
> 
> I'm closing it as it's not the issue.

If I want to upgrade to the new version, but also need to achieve the animation effect like 1.0.4, which parameter should I modify?

**Comment by rafalbednarczuk** [comment]
> > Okay, I understand that. This is done on purpose, so user can not change the page when current page change is already in progress.
> > I think I might improve it in future, so it's still possible to click on different page while the current page is changing.
> > For now, you can use 1.0.4 or maybe change duration of animation so it takes less amount of time to change the page again.
> > I'm closing it as it's not the issue.
> 
> If I want to upgrade to the new version, but also need to achieve the animation effect like 1.0.4, which parameter should I modify?

It's not possible at the moment. Either you use 1.0.4 or newer versions with new animation
