### ISSUE TITLE
Bug in release mode

### ISSUE THREAD

**Issue by hosein-nadali** [rafalbednarczuk/curved_navigation_bar#147]
First thanks for this awesome package.
i using this in my project. In debug mode everything are good but when i release APK and install on device, app force exit with this error:
libc --> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20384 (1.ui)

**Comment by rafalbednarczuk** [comment]
This problem looks like not related to the package itself.

Could you reproduce the same with `example` project from this repository? 
Please clone this project locally and run `example/main.dart` in release mode.

If you can reproduce on `example` project or have any other minimal reproducible code, please write a comment, I'll reopen the issue.
