### ISSUE TITLE
Can assertion for index be removed?

### ISSUE THREAD

**Issue by lcundiff** [rafalbednarczuk/curved_navigation_bar#148]
The assertion requiring initial index to be less than the items.length and 0>= is not allowing for setting an unselected navbar (unless there is another way to do this?). 

When I run the app in profile mode, the nav bar can work fine with being unselected, but in debug mode, the assertion runs and fails even though it seems to handle -1 being passed as an index. 

The reason is to allow user to use navbar even if the page they are on, isn't one of the pages listed on the bottom. My temporary solution is passing the parent index in manually. Let me know if I can clarify further.

**Comment by rafalbednarczuk** [comment]
I tested passing `-1` value with the assertion removed and in profile mode.
This causes 
```
I/flutter (11448): RangeError (length): Invalid value: Not in inclusive range 0..4: -1
```

I don't plan to implement such a feature for now as there is not a lot of demand for that.

**Comment by lcundiff** [comment]
@rafalbednarczuk what is recommended for when you are on a page in the app that is not one of the pages on toolbar, outside of not showing toolbar? 

I can also send a screenshot later of the curve bar without a selected index as it worked properly, but perhaps I can pin point how exactly that occurred

**Comment by rafalbednarczuk** [comment]
> @rafalbednarczuk what is recommended for when you are on a page in the app that is not one of the pages on toolbar, outside of not showing toolbar?

I have no idea because I didn't have such a case. I would hide a toolbar if user was on a page that isn't available on a toolbar.


> I can also send a screenshot later of the curve bar without a selected index as it worked properly, but perhaps I can pin point how exactly that occurred

Please send a screenshot
