### ISSUE TITLE
set number  items to 4  will cause error in animation and click on icons

### ISSUE THREAD

**Issue by TaifRaoof** [rafalbednarczuk/curved_navigation_bar#18]
when i set four icon in navigation the animation movement will not work correctly and also when i click on icons. so how to solve this problem ?
but when i set item to 3 or 5 it will work correctly.

**Comment by rafalbednarczuk** [comment]
What error? Can you explain it more clearly?

**Comment by TaifRaoof** [comment]
i solved this problem by changing the icons size the height of navigation.
