### ISSUE TITLE
add padding or margin to icons in navigation that not active 

### ISSUE THREAD

**Issue by TaifRaoof** [rafalbednarczuk/curved_navigation_bar#19]
I want to add padding to the icons in the navigation because i use custom icons that it is appear attached to the border of navigation

**Comment by rafalbednarczuk** [comment]
It's been fixed months ago. Now Icons are centered by default.

**Comment by BJSam** [comment]
@rafalbednarczuk I still ahve this issue they are not in center.

![Screenshot (8)](https://user-images.githubusercontent.com/20676057/129311838-138d3073-a4d0-4c25-bc22-466c4868db54.png)


my code 

```
CurvedNavigationBar(
        color: K.kPrimaryColor,
        items: _options,
        backgroundColor: Colors.white,
        buttonBackgroundColor: K.kPrimaryColor,
        onTap: (int index){
          _currentIndex= index;
          print(_currentIndex);
        },

      ),
```
