### ISSUE TITLE
How to animate based on the swiping movements of the tabbarview?

### ISSUE THREAD

**Issue by momoDragon** [rafalbednarczuk/curved_navigation_bar#21]
As we know there are two ways to navigate tabBarView. One is by clicking the tab handle and one is by swipping. With your package i am able to click on the icon to navigate. But how do i swipe to navigate while animating the curve navigation bar icons?

**Comment by rafalbednarczuk** [comment]
It's not possible with current version of CurvedNavigationBar. There must be added some PageController param to the CurvedNavigationBar in order to handle swiping or some other solution. Feel free to make pull request.

**Comment by gepd** [comment]
It's possible to change the button position with a tab widget: 

1. put the code in a statefull widget 
2. create a state ex. `currentPage` set this state on the `index` attribute of the curved navigation bar
3. change this state when the page is swapped

**Comment by pooya144** [comment]
dear @gepd 
please send me an example code of curved navigation bar with swiping 
thanks.

**Comment by gepd** [comment]
@pooya144 this is how I did it

```dart
class _MyAppState extends State<MyApp> {
  static int _currentPage = 0; // this will move the navigation bar to the current index

  static final PageController _pageController = PageController(
    initialPage: _currentPage,
    keepPage: true,
  );

  Widget buildPageView() {
    return PageView(
      controller: _pageController,
      onPageChanged: (index) {
        setState(() {
          _currentPage = index; // update index when swap
        });
      },
      children: <Widget>[
        // Your pages
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: CurvedNavigationBar(
        index: _currentPage, // update bottom bar index
        items: <Widget>[
          // your icons
        ],
        onTap: (index) {
          setState(() {
            _pageController.jumpToPage(index); // move page when you press a button
            _currentPage = index; // and update the index
          });
        },
      ),
      body: // your body,
      extendBody: true,
    );
  }
}
```

**Comment by pooya144** [comment]
@gepd thank you so much  but did you change the package code?
it not have "index" attribute and give error for that

**Comment by pooya144** [comment]
@gepd  thank you so much for your guidance first i used another curved navigation bar package that not have "index" attribute but when use this package  my problem has been resolved

**Comment by cn-Meepo** [comment]
@gepd that's great.
