### ISSUE TITLE
Curved Navigation Bar problem with RTL (Arabic) Languages

### ISSUE THREAD

**Issue by AmmarAl-Wazzan** [rafalbednarczuk/curved_navigation_bar#24]
hi ...
I used it in the Arabic language ... which is RTL layout ... there is a problem ...

the problem is when I have 5 items ... and chose the centred item ... ok

but when I chose second items which its index = 1 ... it animated to the mirror position just like I chose the item 4 which it's index = 3 .... also the first item (index = 0) looks like I choose item 5 (index 4)...

`bottomNavigationBar: CurvedNavigationBar( index: _page, height: 55.0, items: <Widget>[ Icon(Icons.info, size: 25,color: Colors.white,), Icon(FontAwesomeIcons.hashtag, size: 22,color: Colors.white,), Icon(FontAwesomeIcons.briefcaseMedical, size: 20,color: Colors.white,), Icon(FontAwesomeIcons.solidMoon, size: 20,color: Colors.white,), Icon(Icons.account_circle, size: 25,color: Colors.white,), ], color: Colors.cyan, buttonBackgroundColor: Colors.pink, backgroundColor: Colors.white, animationCurve: Curves.easeInOut, animationDuration: Duration(milliseconds: 200), onTap: (index) { setState(() { _page = index; }); }, )`

MyRealExample:
![](https://user-images.githubusercontent.com/51271352/58754564-a73ce180-84db-11e9-8287-e89a3456264b.jpg)

Best Regards

**Comment by rafalbednarczuk** [comment]
fixed in 
https://github.com/rafalbednarczuk/curved_navigation_bar/commit/a0901e2f57bb6b714eaa8adec6f71fde1bdc5516
pub updated - version 0.2.20
