### ISSUE TITLE
how to add to the project ...

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [rafalbednarczuk/curved_navigation_bar#27]
sorry for this really basic question but im new to flutter and dont know how to add it to my project.
in first place for adding the dependencies i have this error : Error on line 14, column 3 of pubspec.yaml: A package may not list itself as a dependency.

second where to add that Scaffold(...)

and third  i dont know how to use it in another project ...

i wish you guys can help me with comments or a link to a tutorial 
thank you

**Comment by rafalbednarczuk** [comment]
Add this to your package's pubspec.yaml file:


dependencies:
  curved_navigation_bar: ^0.2.20

Then start new project, replace main.dart with example.dart from this repository, run

**Comment by MojtabaTavakkoli** [comment]
yea tnx.
but when i try to launch the app i get a blank page on android device emulator with error :" [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:peyk_v1_0_1/main.dart': Failed assertion: line 32 pos 16: 'items != null': is not true."  in the console. 


I'm using android studio.
    On Monday, June 3, 2019, 9:20:20 PM GMT+1, rafalbednarczuk <notifications@github.com> wrote:  
 
 
Add this to your package's pubspec.yaml file:

dependencies:
curved_navigation_bar: ^0.2.20

Then start new project, replace main.dart with example.dart from this repository, run

**Comment by rafalbednarczuk** [comment]
replace main.dart with example.dart from this repository, run

**Comment by MojtabaTavakkoli** [comment]
tnx for ur time :)
   On Wednesday, June 5, 2019, 3:00:41 AM GMT+4:30, rafalbednarczuk <notifications@github.com> wrote:  
 
 
replace main.dart with example.dart from this repository, run
