### ISSUE TITLE
How to navigate through pages without clicking on the Navigation Bar itself?

### ISSUE THREAD

**Issue by prafgup** [rafalbednarczuk/curved_navigation_bar#29]
I wanted to go to a certain page from onPressed of a widget in the drawer how can i implement this?

**Comment by varadkulk** [comment]
`class HomeState extends State<Home> {`
`  int _selectedPage = 0;`
`  final _pageOptions = [HomePage(), attendence(), Setting()];`//Add your pages here
`  @override`
`  Widget build(BuildContext context) {`
`    return new MaterialApp(`
`      home: new Scaffold(`
`        body: _pageOptions[_selectedPage],`
`        bottomNavigationBar: CurvedNavigationBar(`
`          onTap: (int index) {`
`            setState(`
`              () {`
`                _selectedPage = index;`
`              },`
`            );`
`          },`
`          items: <Widget>[`
`            Icon(Icons.add, size: 30)`,
`            Icon(Icons.list, size: 30),`
`            Icon(Icons.compare_arrows, size: 30),`
`          ],),),);}}`



This will help

**Comment by prafgup** [comment]
I said I wanted to navigate to another tab from the click of a button in Drawer class without clicking on the BottomNavigation bar ,
Eg, From the class drawer()
 somebutton{onpressed: (){ do something so the current visible page changes to the page at index 4}}

Can you help with the function required to do this?

**Comment by sutejoramadhan** [comment]
if you mean like this

![ezgif-2-2d004c8e1034](https://user-images.githubusercontent.com/22488124/59149177-8bd25900-8a3c-11e9-9c09-0e331229a1a3.gif)

you should pass the argument that reference index number your nav item from wherever widget. i use route style to navigate in my app, then put this code in ontap to navigate to other navigation item: 
Navigator.of(context).pushReplacementNamed('/main',` arguments: {"index": 3, "data": null});

**Comment by varadkulk** [comment]
### This are the classes containing bottom navigation

`class Home extends StatefulWidget {`
`  int selectedPage = 0;`
`  Home({this.selectedPage = 0});`
`  @override`
`  State createState() => new HomeState();`
`}`

`class HomeState extends State<Home> {`
`  final _pageOptions = [...];`
`  @override`
`  Widget build(BuildContext context) {`
`    return new MaterialApp(`
`      home: new Scaffold(`
`        body: _pageOptions[widget.selectedPage],`
`        bottomNavigationBar: CurvedNavigationBar(`
`          index: widget.selectedPage,`
`          onTap: (int index) {`
`            setIndex(index);`
`          },`
`          items: <Widget>[...],),),);}`

  `setIndex(int index) {`
    `print(index);`
    `setState(
      () {`
       ` widget.selectedPage = index;`
      `},);}}`

### And for onPressed:

`RaisedButton(
            onPressed: () => {`
                 ` Navigator.pop(context),
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (BuildContext context) => Home(`
                              `selectedPage: 4,`
`)),),},),`

**Comment by prafgup** [comment]
Isn't there any optimum solution for this than Building the whole Home again and again ? 
Like in another package fancy_bottom_navigation it provides this function to change the page without having to push the home page again.

` onPressed: () {`
               ` final FancyBottomNavigationState fState =`
                    `bottomNavigationKey.currentState;`
                `fState.setPage(2);`
             ` },`

**Comment by varadkulk** [comment]
> Isn't there any optimum solution for this than Building the whole Home again and again ?
> Like in another package fancy_bottom_navigation it provides this function to change the page without having to push the home page again.
> 
> ` onPressed: () {`
> ` final FancyBottomNavigationState fState =`
> `bottomNavigationKey.currentState;`
> `fState.setPage(2);`
> ` },`

[Try something like this](https://medium.com/@lucassaltoncardinali/keeping-state-with-the-bottom-navigation-bar-in-flutter-69e4168878e1)

**Comment by prafgup** [comment]
@varadkulk @sutejoramadhan 
I fixed the problem and now you can change the page from anywhere without having to push every time.
Check it out here I have also mentioned how to use it.

 https://github.com/rafalbednarczuk/curved_navigation_bar/pull/32

**Comment by abdelrahmanelmarakby** [comment]
> `class HomeState extends State<Home> {`
> ` int _selectedPage = 0;`
> ` final _pageOptions = [HomePage(), attendence(), Setting()];`//Add your pages here
> ` @override`
> ` Widget build(BuildContext context) {`
> ` return new MaterialApp(`
> ` home: new Scaffold(`
> ` body: _pageOptions[_selectedPage],`
> ` bottomNavigationBar: CurvedNavigationBar(`
> ` onTap: (int index) {`
> ` setState(`
> ` () {`
> ` _selectedPage = index;`
> ` },`
> ` );`
> ` },`
> ` items: <Widget>[`
> ` Icon(Icons.add, size: 30)`,
> ` Icon(Icons.list, size: 30),`
> ` Icon(Icons.compare_arrows, size: 30),`
> ` ],),),);}}`
> 
> This will help

thanks very much for that example you are a hero to me

**Comment by prafgup** [comment]
https://github.com/rafalbednarczuk/curved_navigation_bar/pull/32

Fixed the problem , closing this issue as of now.
