### ISSUE TITLE
Looks great if we can also add backgroundColor to transparent

### ISSUE THREAD

**Issue by ShashankSirmour** [rafalbednarczuk/curved_navigation_bar#3]
it's already looking very awesome but if we can assign a transparent background color for floating button then looks more beautiful in some cases. please implement transparent background color for floating button if it can be possible.

**Comment by rafalbednarczuk** [comment]
Thanks for those issues! They are improving widget.

Commit which implement it should:
- add new parameter buttonBackgroundColor
- remove elevation from Material wrapping floating button
- change readme, example, changelog

It's easy job so pull requests are welcome :)
If noone takes it I will do it tommorow

**Comment by rafalbednarczuk** [comment]
fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/9f70b39a5bb0119136c237afca4a807f312ca440
