### ISSUE TITLE
InkWell optional Splash effect

### ISSUE THREAD

**Issue by dali546** [rafalbednarczuk/curved_navigation_bar#30]
The `nav_button.dart` file has an InkWell with a SplashColour. It doesnt look nice when you have a SizedBox of 100.0 and the bar of only 75.0

Could this SplashColour be removed? or possibly one of the following

- Expose Properties of `NavButton` so it can be customized and used with the NavBar
- Change the NavButton to also be circular, but Infront of the `NavCustomPainter` (may look better when Splash is over and not hidden behind
```
child: InkWell(
        splashColor: Colors.transparent,
        highlightColor: Colors.transparent,
        onTap: () {
          onTap(index);
        },
        child: Container(
```
[https://github.com/rafalbednarczuk/curved_navigation_bar/blob/master/lib/src/nav_button.dart#L19](source)

**Comment by Jayant2204** [comment]
https://github.com/Jayant2204/curved_navigation_bar/blob/master/lib/src/nav_button.dart

Check this solution.

**Comment by rafalbednarczuk** [comment]
fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/3d76ab4f2f5baf28087370879763f76cd8eb02f7
