### ISSUE TITLE
How to make the background color transparent

### ISSUE THREAD

**Issue by kosytedy** [rafalbednarczuk/curved_navigation_bar#31]
Please how can someone make the Navigation bar background color to be transparent? 

I have tried Colors.transparent and .withOpacity(0.0) but they don't work.

Please how can I solve this?

Something like this:
<img width="408" alt="transparent-nav" src="https://user-images.githubusercontent.com/13806970/60248360-1a8e0500-9888-11e9-8015-640a0d11dc08.png">

**Comment by rafalbednarczuk** [comment]
if you want background of navigation bar transparent use:
```
Scaffold(
      //...
      extendBody: true,
        bottomNavigationBar: CurvedNavigationBar(
          //...
          backgroundColor: Colors.transparent,
           ))
```

**Comment by kosytedy** [comment]
Works great!

**Comment by rishabhdavesar** [comment]
doesn't work for me

**Comment by g-akshay** [comment]
It's not working... Please tell the alternative approach

**Comment by g-akshay** [comment]
`extend: true` along with. transparent colour works perfectly!!! 
I was facing the same issue, later found out the height of the container was not enough to be overlapped by the bottom navigation bar. Increasing the container height resolved the issue for me.

Hope it helps !!!

**Comment by Anigulig** [comment]
@rishabhdavesar  In other case you can use 
```dart
canvasColor: Colors.transparent;
``` 
In **ThemeData** of your application. 
These changes helped in my case.

**Comment by AnnaPS** [comment]
> if you want background of navigation bar transparent use:
> 
> ```
> Scaffold(
>       //...
>       extendBody: true,
>         bottomNavigationBar: CurvedNavigationBar(
>           //...
>           backgroundColor: Colors.transparent,
>            ))
> ```

You save my day! Thanks

**Comment by nscar** [comment]
Ctrl + Click ---> CurvedNavigationBar .... change color.

**Comment by nscar** [comment]
Ctrl + Click CurvedNavigationBar 

this.backgroundColor = Colors.transparent,

**Comment by partitect** [comment]
> if you want background of navigation bar transparent use:
> 
> ```
> Scaffold(
>       //...
>       extendBody: true,
>         bottomNavigationBar: CurvedNavigationBar(
>           //...
>           backgroundColor: Colors.transparent,
>            ))
> ```

It worked perfectly

**Comment by KriacoesMobile** [comment]
> if you want background of navigation bar transparent use:
> 
> ```
> Scaffold(
>       //...
>       extendBody: true,
>         bottomNavigationBar: CurvedNavigationBar(
>           //...
>           backgroundColor: Colors.transparent,
>            ))
> ```

Thanks work fine here too. ;)

**Comment by itsdani121** [comment]
> doesn't work for me

have you found solution i also facing the same problem. i tried all above solution but not work for me

**Comment by cybex-dev** [comment]
see #115, specifically I have a solution for this issue (chances are those who can't get it working are using a `SafeArea`)

https://github.com/rafalbednarczuk/curved_navigation_bar/issues/115#issuecomment-1019638165
