### ISSUE TITLE
add SafeArea Widget before CurvedNavigationBar 

### ISSUE THREAD

**Issue by TaifRaoof** [rafalbednarczuk/curved_navigation_bar#35]
Hi
when i add SafeArea Widget before CurvedNavigationBar the icon appear out of navigation bar and above the safe area bar in iphone xr  this appear only when i click icons , i think should prevent icon across the navigation and don't appear outside during transition between icons.... so how to solve this problem.
thank you

**Comment by AndrewPiterov** [comment]
The same with  `curved_navigation_bar: ^0.3.7`

**Comment by AndrewPiterov** [comment]
But I guess, @TaifRaoof you can use `height` parameter, but max is 75 😂
