### ISSUE TITLE
This is not issue.Asking for help.How to show dart file.I hvae 4 dart file.Home.dart,faq.dart and so on.when change navigation i want chane dart file.Please help me.

### ISSUE THREAD

**Issue by heinzan** [rafalbednarczuk/curved_navigation_bar#36]

**Comment by heinzan** [comment]
import 'package:flutter/material.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart';
import 'faq_page.dart';
import 'health_page.dart';
import 'video_page.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _HomeState();
  }
}

class _HomeState extends State<HomePage> {
  final List<Widget> pages = [
    HomePage() ,
    VideoPage() ,
    HealthPage() ,
    FaqPage(),
  ];

  int _page = 0;
  GlobalKey _bottomNavigationKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(title: Text('Home'), backgroundColor: Colors.pinkAccent),
      bottomNavigationBar: CurvedNavigationBar(
        key: _bottomNavigationKey,
        backgroundColor: Colors.pinkAccent,
        items: <Widget>[
          Icon(Icons.library_books, size: 30),
          Icon(Icons.hd, size: 30),
          Icon(Icons.local_hospital, size: 30),
          Icon(Icons.feedback, size: 30),
        ],
        onTap: (index) {
          setState(() {
            _page = index;
          });
          //Handle button tap
        },
      ),
      body: pages[_page],
    );
  }
}
This is my main dart file.

import 'package:flutter/material.dart';

class VideoPage extends StatelessWidget{
  const VideoPage({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text("First Screen"),
      ),
      body: ListView.builder(itemBuilder: (context , index){
        return ListTile(
          title: Text('Lorem Ipsum'),
          subtitle: Text('$index'),
        );
      }),
      
    );
  }
  
}
this is sub dart file

**Comment by bl4ckck** [comment]
I think your code's correct. Where's the problem?. You can try these codes


**Use var**
```
var condts = {
    0: FirstTab(),
    1: SecondTab(),
    2: ThirdTab(),
  };
```

**Use Widget**
```
Widget pageScreens(int index) {
    switch (index) {
      case 0:
        return FirstTab();
      case 1:
        return SecondTab();
      case 2:
        return ThirdTab();
    }

    throw "Invalid index $index";
  }
```
