### ISSUE TITLE
Tap on the same icon again

### ISSUE THREAD

**Issue by brunokitaka** [rafalbednarczuk/curved_navigation_bar#38]
I'm using this package in a bottom bar. When an icon is selected its gesture detector is dragged down, so it's very diffucult to tap it again.
I would like to know if it's possible to maintain the gesture detector in the same position as the selected icon.

**Comment by rafalbednarczuk** [comment]
good point

**Comment by Azzeccagarbugli** [comment]
Yeah, I'm realising that unfortunately as @brunokitaka said the gesture detection is really dragged down so it's **really difficult** to tap on it. I really would like to know how to fix it or simply wait for a new update!

**Comment by rafalbednarczuk** [comment]
It's fixed for months
