### ISSUE TITLE
Feature Request: Add the possibility to set a gradient for the bottomNavigation color

### ISSUE THREAD

**Issue by filipeteotonio** [rafalbednarczuk/curved_navigation_bar#49]
First of all I'd like to thank you for the amazing job you've done. I was playing with it these days and I realised that we could add much more life if we could set a gradient to the colors of the navigation bar.

**Comment by filipeteotonio** [comment]
I've implemented that. If you want I can make a PR.

**Comment by rafalbednarczuk** [comment]
Cool, let me see it
