### ISSUE TITLE
backgroundColor should have transparent color 

### ISSUE THREAD

**Issue by ShashankSirmour** [rafalbednarczuk/curved_navigation_bar#5]
I think if anyhow we can do backgroundColor to transparent then it automatically adapts to screen background color.  I tried to assign a backgroundColor to transparent but it still white please implement it. 

![Screenshot (33)_LI](https://user-images.githubusercontent.com/47277747/54299253-8782d500-45e0-11e9-8c69-ceba0afb64a1.jpg)

**Comment by rafalbednarczuk** [comment]
you can can use
```
Scaffold(
      extendBody: true,
      )

```
and Color.transparent as backgroundColor of CurvedNavigationBar.
Let me know if this is what you are asking for.

**Comment by ShashankSirmour** [comment]
yes, it works with resizeToAvoidBottomPadding: true as you said thank you very much.

**Comment by marchpanda123** [comment]
> you can can use
> 
> ```
> Scaffold(
>       extendBody: true,
>       )
> ```
> and Color.transparent as backgroundColor of CurvedNavigationBar.
> Let me know if this is what you are asking for.

i have the same issues, if i use listview in the body, the backgroundColor will not be transparent....

**Comment by ShashankSirmour** [comment]
yes, 

> > you can can use
> > ```
> > Scaffold(
> >       extendBody: true,
> >       )
> > ```
> > and Color.transparent as backgroundColor of CurvedNavigationBar.
> > Let me know if this is what you are asking for.

> I have the same issues, if I use listview in the body, the backgroundColor will not be transparent...

yes, same here in case of list view list is not rendering behind floating button it's just showing the scaffold background color.

**Comment by rafalbednarczuk** [comment]
```
    return Scaffold(
      extendBody: true,
      bottomNavigationBar: CurvedNavigationBar(
        initialIndex: 0,
        items: <Widget>[
          Icon(Icons.add, size: 30),
          Icon(Icons.list, size: 30),
          Icon(Icons.compare_arrows, size: 30),
          Icon(Icons.call_split, size: 30),
          Icon(Icons.perm_identity, size: 30),
        ],
        backgroundColor: Colors.transparent,
      ),
      body: ListView.builder(itemBuilder: (context, index) => Text("test")),
    );

```
Above example will work for you. You have to make extendBody: true parameter in Scaffold and also backgroundColor: Colors.transparent in CurvedAnimationBar.
Don't forget to update version of curved_navigation_bar in pubspec to newest
