### ISSUE TITLE
Docked FloatingActionButton

### ISSUE THREAD

**Issue by egprojects** [rafalbednarczuk/curved_navigation_bar#53]
It'd be cool if you'll make  setting docked FAB like with standard BottomNavigationBar possible. Now it just goes over NavBar.

![5](https://user-images.githubusercontent.com/38351048/73867338-9822e600-4857-11ea-8c42-d1e864469021.jpg)

**Comment by marcoberetta96** [comment]
Found any solution?

**Comment by rafalbednarczuk** [comment]
just use FAB in body of scaffold inside Stack and set Padding to it.
