### ISSUE TITLE
OnSwipe Next tab screen is visible but ,  tab is not changed. 

### ISSUE THREAD

**Issue by Flutter-Stack** [rafalbednarczuk/curved_navigation_bar#56]
I have configured curved navigation bar. Ontap the tab is changing and and the content of  next tab is visible.

but on swipe the content is changed but **current tab is not changed**.

`class Dashboard extends StatefulWidget {
  @override
  _DashboardState createState() => _DashboardState();
}

class _DashboardState extends State<Dashboard> {

  final int _page = 1;
  GlobalKey _bottomNavigationKey = GlobalKey();
  final _pageController = PageController(initialPage: 1);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // backgroundColor: Colors.grey,
      appBar: BaseAppBar(
        elevation: 0.5,
        appBar: AppBar(),
        backgroundColor: Colors.white,
        // title: ,
      ),
      bottomNavigationBar: CurvedNavigationBar(
        key: _bottomNavigationKey,
        backgroundColor: Colors.white,
        buttonBackgroundColor: Colors.blue[500],
        color: Color.fromRGBO(206, 206, 206, 0.5),
        index: _page,
        items: <Widget>[
          Icon(Icons.terrain, size: 50, color: Colors.grey,),
          Icon(Icons.perm_media, size: 50, color: Colors.grey,),
          Icon(Icons.local_offer, size: 50, color: Colors.grey,),
          Icon(Icons.account_circle, size: 50, color: Colors.grey, ),
        ],
        onTap: (int index) {
          setState(() {
            _pageController.jumpToPage(index);
          });
        },
      ),
      body: PageView(
        controller: _pageController,
        children: <Widget>[
          MoneyPlant(),
          Adds(),
          Discounts(),
          Profile(),
        ],
        onPageChanged: (int index) {
          setState(() {
            _pageController.jumpToPage(index);
          });
        }
      ),
    );
  }
`

**Comment by ElasticBottle** [comment]
Hi, these seems to be similar to #21 . Maybe check out that solution?

**Comment by rafalbednarczuk** [comment]
duplicate to https://github.com/rafalbednarczuk/curved_navigation_bar/issues/21
