### ISSUE TITLE
i cant change the backround to transparent

### ISSUE THREAD

**Issue by grupoinnovar** [rafalbednarczuk/curved_navigation_bar#58]
I have a proble when one of my pages are scrolleable, the effect of curved slide around turns white when i put this code bdw im new on flutter its posible turn transparent for the scrollview?:

Scaffold(
        
        bottomNavigationBar: CurvedNavigationBar(
          index: pageIndex,
          height: 50.0,
          items: <Widget>[
            Icon(Icons.home, size: 30, color: Colors.greenAccent),
            Icon(Icons.list, size: 30, color: Colors.greenAccent),
            Icon(Icons.calendar_today, size: 30, color: Colors.greenAccent),
            Icon(Icons.map, size: 30, color: Colors.greenAccent),
            Icon(Icons.perm_identity, size: 30, color: Colors.greenAccent),
          ],
          color: Colors.deepPurple,
          buttonBackgroundColor: Colors.deepPurple,
          backgroundColor: Colors.transparent,
          animationCurve: Curves.bounceInOut,
          animationDuration: Duration(milliseconds: 300),
          // onTap para que navegue en las pestañas de buttonnavigatonBar
          onTap: (int tappedIndex) {
            setState(() {
              _showPage = _pageChooser(tappedIndex);
            });
          },
        ),

![91007085_638290240286751_1162938983248822272_n](https://user-images.githubusercontent.com/17199515/77615428-61835680-6efd-11ea-951f-5b4d230b1acf.jpg)

**Comment by rafalbednarczuk** [comment]
Answered in https://github.com/rafalbednarczuk/curved_navigation_bar/issues/31

**Comment by alejandrop1105** [comment]
hi , if add "extendBody: true" in you Scaffold and background not transparent, is for SafeArea widget in the body of the Scaffold
