### ISSUE TITLE
fix option

### ISSUE THREAD

**Issue by shinriyo** [rafalbednarczuk/curved_navigation_bar#59]
Does it have fix option?

**Comment by rafalbednarczuk** [comment]
what do you mean by fix option?

**Comment by rafalbednarczuk** [comment]
might be related to https://github.com/rafalbednarczuk/curved_navigation_bar/issues/61

**Comment by shinriyo** [comment]
I forgot my question

**Comment by rafalbednarczuk** [comment]
probably fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/d5e428b17d03049a0c9cdd055224f97921ad6b03
