### ISSUE TITLE
Fixed Option

### ISSUE THREAD

**Issue by MirzayevFarid** [rafalbednarczuk/curved_navigation_bar#61]
Is there an option for fixed animation? Thus, the blue background (color) does not change to the icon selected as in the image.

![Screen Shot 2020-04-06 at 03 46 59](https://user-images.githubusercontent.com/29518613/78514298-4a741c80-77b9-11ea-8aee-7ccd4b661772.png)

**Comment by rafalbednarczuk** [comment]
fixed in https://github.com/rafalbednarczuk/curved_navigation_bar/commit/d5e428b17d03049a0c9cdd055224f97921ad6b03

**Comment by shinriyo** [comment]
thank you
