### ISSUE TITLE
Tap on the same item in CurvedNavigationBar build related page again

### ISSUE THREAD

**Issue by NickanBagherpour** [rafalbednarczuk/curved_navigation_bar#62]
Hi
As I mentioned in title , when I tap on the same item in CurvedNavigationBar , the whole page build triggers again and that's not good , especially when that page does some heavy networking or etc.
It is not possible to prevent page changing in onTap function ...
I hope you can understand my purpose
Thank you

**Comment by rafalbednarczuk** [comment]
You should specify rebuild behavior inside `onTap(index)` method of `CurvedNavigationBar`. If the index is the same as before then don't rebuild the page.
