### ISSUE TITLE
Error when using mediaquery.of(context).size.height * 0.15 in curved navigation bar

### ISSUE THREAD

**Issue by phaneendra-rao** [rafalbednarczuk/curved_navigation_bar#71]
How to add mediaquery height to height property in curved navigation bar ?

I tried using media query but it is throwing error :(

package:curved_navigation_bar/curved_navigation_bar.dart': Failed assertion: line 31 pos 16: '0 <= height && height <= 75.0

**Comment by rafalbednarczuk** [comment]
height has to be smaller than 75.0 and larger than 0.0. 
Try 
`mediaquery.of(context).size.height * 0.15 > 75.0 ? 75.0 : mediaquery.of(context).size.height * 0.15`
instead of 
`mediaquery.of(context).size.height * 0.15`

**Comment by ebad-ahmed-progatix** [comment]
What if we need height more than 75?
