### ISSUE TITLE
Can i change the width of this navigation bar?

### ISSUE THREAD

**Issue by OmiWakode** [rafalbednarczuk/curved_navigation_bar#73]
I want to use this nav bar somewhere else, not at the bottom, is there any way i could do this?

**Comment by rafalbednarczuk** [comment]
How do you want to use it?

**Comment by OmiWakode** [comment]
I wanted to use it in my web page, as a top navigation bar, not the same width as the screen

**Comment by rafalbednarczuk** [comment]
Wrap it with `Container` and set  `Container`'s width

**Comment by OmiWakode** [comment]
I have already tried it!!! It does change the width but the icon and it's animation does not change
The icons behave according to the width of my screen
If you wish i can attach the ss

**Comment by rafalbednarczuk** [comment]
Okay, I see. I'm open for pull requests in this case.

**Comment by andre-ab** [comment]
Look:
https://github.com/rafalbednarczuk/curved_navigation_bar/pull/133
