### ISSUE TITLE
CurvedNavigationBar in StatelessWidget 

### ISSUE THREAD

**Issue by divid0n1** [rafalbednarczuk/curved_navigation_bar#74]
Hi - I am unable to embed Curved Navigation Bar code in StatelessWidget as Curved Navigation Bar using setState() method from StatefullWidget which one can't be used in StatelessWidget. Can anybody give me alternate way of setState to navigate different page from NavigationBar. Thank you.

**Comment by rafalbednarczuk** [comment]
that's not CurvedNavigatorBar issue.

**Comment by divid0n1** [comment]
Yes sir its not issue but I want to embed it stateless widget, can please help me to apply this, your support will be highly appreciated.

**Comment by rafalbednarczuk** [comment]
please ask on stackoverflow
