### ISSUE TITLE
Animate only icons

### ISSUE THREAD

**Issue by marcoprodata** [rafalbednarczuk/curved_navigation_bar#76]
Dears,

Firstly, sorry for my bad english, is possible to animate only icons while jump to page? I have five icons in my bottom, and when navigate from the first to the last, the middle pages are loaded while navigation is happening, so, i need to animate only the icons to prevent the process in the build of the middle pages.

**Comment by rafalbednarczuk** [comment]
Curved Navigation Bar isn't related to your page handling solution.
