### ISSUE TITLE
missed up

### ISSUE THREAD

**Issue by barzansaeedpour** [rafalbednarczuk/curved_navigation_bar#8]
when i use (  supportedLocales: [const Locale("fa", "IR")],) for my MaterialApp the buttonNavigationBar misses up

**Comment by rafalbednarczuk** [comment]
This widget dosen't utilize locales and that's why you see warning, but it has no effect on this widget.

**Comment by barzansaeedpour** [comment]
when i tap the first index it will choose the wrong one. in LTR mode it has no problem but i want this package for RTL mode.
