### ISSUE TITLE
Cant compile for Windows.

### ISSUE THREAD

**Issue by Shiba-Kar** [rafalbednarczuk/curved_navigation_bar#81]
```/C:/flutter/.pub-cache/hosted/pub.dartlang.org/curved_navigation_bar-0.3.4/lib/curved_navigation_bar.dart(95,9): error GBF4691A2: No named parameter with the name 'overflow'. [C:\Programming\Flutter\adminbscit\build\windows\flutter\flutter_assemble.vcxproj] ```

**Comment by prafgup** [comment]
Change your flutter channel to stable instead of master. 

This is a known issue here https://github.com/flutter/flutter/issues/66135

(Will Migrate this Plugin to use clipBehavior: Clip.none instead of overflow soon. )

**Comment by rafalbednarczuk** [comment]
> Change your flutter channel to stable instead of master.
> 
> This is a known issue here [https://github.com/flutter/flutter/issues/66135](url)
> 
> (Will Migrate this Plugin to use clipBehavior: Clip.none instead of overflow soon. )

cool, I'm waiting for pull request

**Comment by prafgup** [comment]
@rafalbednarczuk 
Overflow has been added again but as deprecated. https://github.com/flutter/flutter/pull/66305
I will create a PR to use clipBehavior but you should wait for sometime before merging as it may break old flutter version support.

**Comment by Shiba-Kar** [comment]
> Change your flutter channel to stable instead of master.
> 
> This is a known issue here [flutter/flutter#66135](https://github.com/flutter/flutter/issues/66135)
> 
> (Will Migrate this Plugin to use clipBehavior: Clip.none instead of overflow soon. )

I am in dev. I was just trying to build for windows. I always work in stable only.

**Comment by aymenbs2** [comment]
hey any update please

**Comment by rafalbednarczuk** [comment]
fixed in 0.3.5
