### ISSUE TITLE
[Question] Can we achieve this animation?

### ISSUE THREAD

**Issue by qzaeem** [rafalbednarczuk/curved_navigation_bar#84]
I'm looking for a way to achieve this animation for transitioning: 

https://pin.it/5fxp7Nq

![Skype_Picture_2020_10_20T13_56_13_892Z](https://user-images.githubusercontent.com/64101303/96597115-e228fa80-1306-11eb-853e-d3122ecb9f2e.jpeg)

**Comment by rafalbednarczuk** [comment]
@qzaeem hand me an animation instead of an image
