### ISSUE TITLE
Floating action button

### ISSUE THREAD

**Issue by marcoberetta96** [rafalbednarczuk/curved_navigation_bar#85]
How can I put the green FloatingActionButton on the top of the CurvedNavigationBar?
Using a SafeArea in which putting the Scaffold with the FloatingActionButton is not a solution because I need to see the body of the Scaffold through the transparent CurvedNavigationBar.

![Screenshot from 2020-11-04 21-56-29](https://user-images.githubusercontent.com/11749393/98167454-61165980-1ee9-11eb-8620-332599d8f2eb.png)

Thanks!

**Comment by prafgup** [comment]
@marcoberetta96 try this - [https://stackoverflow.com/questions/53463461/how-to-set-custom-offset-to-floatingactionbuttonlocation-in-the-scaffold-in-f](url)

**Comment by marcoberetta96** [comment]
@prafgup it works thank you :)
