### ISSUE TITLE
error :  _bottomNavigationKey.currentState;

### ISSUE THREAD

**Issue by Krahost** [rafalbednarczuk/curved_navigation_bar#87]
I am try to implement the bottom in my project and i keep getting this error, please help me fix it 

 _bottomNavigationKey.currentState;

![image](https://user-images.githubusercontent.com/33775619/99834271-48bb6580-2b9e-11eb-9e57-d7f875bf230c.png)

**Comment by rafalbednarczuk** [comment]
https://pub.dev/packages/curved_navigation_bar/example
Here is how to use _bottomNavigationKey

pt., 20 lis 2020 o 19:09 Krahost <notifications@github.com> napisał(a):

**Comment by Krahost** [comment]
I COPIED THIS WHOLE CODE AND ADDED THE PACKAGE TO MY PUBSPEC.YAML FILE  and i got this same error: below is the code :


import 'package:flutter/material.dart';
import 'package:curved_navigation_bar/curved_navigation_bar.dart'

void main() => runApp(MaterialApp(home: BottomNavBar()));

class BottomNavBar extends StatefulWidget {
  @override
  _BottomNavBarState createState() => _BottomNavBarState();
}

class _BottomNavBarState extends State<BottomNavBar> {
  int _page = 0;
  GlobalKey _bottomNavigationKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        bottomNavigationBar: CurvedNavigationBar(
          key: _bottomNavigationKey,
          index: 0,
          height: 50.0,
          items: <Widget>[
            Icon(Icons.add, size: 30),
            Icon(Icons.list, size: 30),
            Icon(Icons.compare_arrows, size: 30),
            Icon(Icons.call_split, size: 30),
            Icon(Icons.perm_identity, size: 30),
          ],
          color: Colors.white,
          buttonBackgroundColor: Colors.white,
          backgroundColor: Colors.blueAccent,
          animationCurve: Curves.easeInOut,
          animationDuration: Duration(milliseconds: 600),
          onTap: (index) {
            setState(() {
              _page = index;
            });
          },
        ),
        body: Container(
          color: Colors.blueAccent,
          child: Center(
            child: Column(
              children: <Widget>[
                Text(_page.toString(), textScaleFactor: 10.0),
                RaisedButton(
                  child: Text('Go To Page of index 1'),
                  onPressed: () {
                    final CurvedNavigationBarState navBarState =
                        _bottomNavigationKey.currentState;
                    navBarState.setPage(1);
                  },
                )
              ],
            ),
          ),
        ));
  }
}

**Comment by rafalbednarczuk** [comment]
you didn't copy the whole `*example/example.dart
<https://github.com/rafalbednarczuk/curved_navigation_bar/blob/master/example/example.dart>`*
file.
Your code is different

pt., 20 lis 2020 o 20:18 Krahost <notifications@github.com> napisał(a):
