### ISSUE TITLE
Circular menu for Icon in items

### ISSUE THREAD

**Issue by Dam0n-DX** [rafalbednarczuk/curved_navigation_bar#89]
https://user-images.githubusercontent.com/68112998/103012508-bb36b100-4561-11eb-9831-ff1ef2e9a8ff.mp4

Can I have a circular menu for any Icon in nav bar , i can't figure it out help

**Comment by rafalbednarczuk** [comment]
CurvedNavigationBar is not suitable to support this kind of widget at the moment
