### ISSUE TITLE
Control the height of CurvedNavigationBar

### ISSUE THREAD

**Issue by panthe** [rafalbednarczuk/curved_navigation_bar#9]
Hi,
this plugin is very awesome.
There is a way to controle the height of CurvedNavigationBar?
In particular I have in the bottom too blank space and I would like reduce it a little bit.
Thanks

**Comment by rafalbednarczuk** [comment]
fixed in 
https://github.com/rafalbednarczuk/curved_navigation_bar/commit/a55b81913ffbfcee9aa5c08465425b6847485e0f

**Comment by ebad-ahmed-progatix** [comment]
It is working perfectly fine on mobiles but on tab on big screen like tv in vertical view,
we are bound to set height from 0 to 75, is there any way we can set height  bigger than 75 ?
