### ISSUE TITLE
letIndexChange false issue

### ISSUE THREAD

**Issue by kauramanp** [rafalbednarczuk/curved_navigation_bar#95]
Hello 
I would like to change the index of the sheet if a particular condition is meet and it should not automatically change the position on tap. For that I have used letIndexChange = false, this in my case is making every item non clickable. Any solution regarding this will be useful.

**Comment by rafalbednarczuk** [comment]
Use index property from the function to control specific button

```
letIndexChange: (index) { 
//if something then 
return true;
//if something else then
return false;
}
```
