### ISSUE TITLE
Is it possible to use the transparent background?

### ISSUE THREAD

**Issue by EliaTolin** [rafalbednarczuk/curved_navigation_bar#96]
Hi!
I try to set a background transparent but it not works.

![image](https://user-images.githubusercontent.com/60351315/111917767-09385380-8a82-11eb-890f-54f924cfc6e5.png)

I wish there was the possibility to set the background behind the selected button transparency.

I am attaching the reference git to the app.

https://github.com/EliaTolin/StatusVaccini

**Comment by EliaTolin** [comment]
sorry I found #31

**Comment by itsdani121** [comment]
i tried every solution at #31 but did not find the solution all answers not work. which you use answer to help you

**Comment by EliaTolin** [comment]
> i tried every solution at #31 but did not find the solution all answers not work. which you use answer to help you

Hi, you check in my repository. I have succeeded

**Comment by itsdani121** [comment]
> > i tried every solution at #31 but did not find the solution all answers not work. which you use answer to help you
> 
> Hi, you check in my repository. I have succeeded

i check it but i could not found new in it can you explain about it what is it? here is mine

                   Scaffold(
            extendBody: true,
            bottomNavigationBar: CurvedNavigationBar(
              color: Color(int.parse('$newColor')),
              backgroundColor: Colors.transparent,
              key: _bottomsKey,
              height: 50,
              items: [
              //items
                  ],
                ),
              ],
              onTap: (index) {
                setState(() {
                  _page = index;
                });
              },
            ),
            body: WillPopScope(
                onWillPop: _onWillPop, child: resultScreens[_page]),
          );

**Comment by EliaTolin** [comment]
Here : 
https://github.com/EliaTolin/StatusVaccini/blob/main/lib/Screens/main_page.dart

**Comment by itsdani121** [comment]
i checked but i dont understand about it bcz all you did i also did
